all: up

up:
	$(MAKE) -C .. up

down:
	$(MAKE) -C .. down

stop:
	$(MAKE) -C .. stop

start:
	$(MAKE) -C .. start

build:
	$(MAKE) -C .. build

status:
	$(MAKE) -C .. status

fclean:
	$(MAKE) -C .. fclean

re:
	$(MAKE) -C .. re

.PHONY: all up down stop start build status fclean re
